version: 2.1

executors:
  movie-api-executor:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/movie-api

jobs:
  test:
    executor: movie-api-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: Install Node Dependencies
          command: npm i
      - run:
          name: Run Linting and Tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
         
  build_deploy:
    executor: movie-api-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "62:9c:44:46:e4:4a:e2:99:f2:9c:eb:55:07:1f:5e:df"
      - checkout
      - run:
          name: Bump package version
          command: |
            git config user.name $CIRCLE_USERNAME
            git config user.email "work-mpconsultants@outlook.com"
            npm version minor -m  "Bump minor version to %s [ci skip]"
            PACKAGE_VERSION="$(node -pe "require('./package.json').version")"
            echo 'export VERSION=$PACKAGE_VERSION' >> $BASH_ENV
            echo 'Version created $VERSION'
            git push origin master
      - run:
          name : Build & Deploy Docker Image
          command: |
            docker build -f ./build/Dockerfile -t movie-api:$VERSION .
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag movie-api:$VERSION registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
            export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
            curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  version: 2
  cd_pipeline:
    jobs:
      - test
      - build_deploy:
          requires:
            - test
          filters:
            branches:
              only: master