version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/movie-api
    steps:
      - checkout

      - run:
          name : Build Docker Image
          command: docker build -t movie-api:$CIRCLE_SHAI
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag movie-api:$CIRCLE_SHAI registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
